name: Construccion Proyecto Netflix

on:
  push:
    branches: feat-lab-oscarolivares-v1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Adjust the runner OS if needed

    steps:
      - uses: actions/checkout@v3  # Checkout your code from GitHub

      - name: Install Java JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Install Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16