name: Construccion Proyecto Netflix

on:
  push:
    branches: feat-lab-oscarolivares-v1

jobs:
# ------------------ Docker Scan ------------------------------------


  DockerScan:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Pull de la Imagen Docker
        run: |
          docker pull oscargitops/netflix:latest
    
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'oscargitops/netflix:latest'
          format: 'table'
    
      - name: Push Docker
        run: | 
          docker push oscargitops/netflix:latest

# ----------------- DAST -----------------------------------------

  DAST: 
    needs: DockerScan
    runs-on: self-hosted
    steps:
      
      - name: OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:80'

    

