name: Construccion Proyecto Netflix

on:
  push:
    branches: feat-lab-oscarolivares-v1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Adjust the runner OS if needed
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout your code from GitHub

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16