name: Construccion Proyecto Netflix

on:
  push:
    branches: feat-lab-oscarolivares-v1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install React dependencies
        run: |
          npm install

      - name: Build React application
        run: |
            npm run build
      
      
      - name: Compilacion MVN
        run: mvn package
      
      - name: Analisis SonarCloud
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=oscargitops \
          -Dsonar.projectKey=OscarGitOps_Laboratorio-final

          
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
            project: '${{ github.event.repository.name }}'
            path: '.'
            format: 'HTML'
            out: 'reports'

      - name: Upload Test result
        uses: actions/upload-artifact@v4
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
      
     
      - name: Run Trivy File System Scan
        run: |
          trivy fs . > trivyfs.txt
 
 
    # docker build --tag oscargitops/netflix:latest .

    #  - name: Docker Login
    #    uses: docker/login-action@v3.2.0
    #    with:
    #        username: ${{ secrets.DOCKER_USER }}
    #        password: ${{ secrets.DOCKER_PASS }}
    # 
    #  - name: Build Docker Image
    #    run: |
    #       docker build --tag oscargitops/netflix:latest .
      
   
 
    
###################################################
 
    #  - name: Build Docker
    #    run: |
    #       docker build --tag oscargitops/netflix:latest .
    #
    #  - name: Push Docker
    #    run: |
    #      docker push oscargitops/netflix:latest

