name: Construccion Proyecto Netflix

on:
  push:
    branches: feat-lab-oscarolivares-v1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

  SAST:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Instalar curl
        run: |
          sudo apt-get update && sudo apt-get install -y curl  
  
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
  
      - name: Checkout code
        uses: actions/checkout@v2
     
    
        
      - name: Run SonarQube analysis
        run: |
           ./gradlew sonarqube \
           -Dsonar.projectKey=${{ github.event.repository.name }} \
           -Dsonar.organization=oscargitops \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
           -Dsonar.branch.name=